eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
    registry-fetch-interval-seconds: 10
spring:
  cloud:
    gateway:
      routes:
       - id: mall-ums
         uri: lb://mall-ums
         predicates:
            - Path=/admin/**
       - id: mall-ums
         uri: lb://mall-ums
         predicates:
            - Path=/role/**
       - id: mall-ums
         uri: lb://mall-ums
         predicates:
            - Path=/menu/**
       - id: mall-ums
         uri: lb://mall-ums
         predicates:
            - Path=/resourceCategory/**
       - id: mall-ums
         uri: lb://mall-ums
         predicates:
            - Path=/resource/**
