server:
  port: 8301
spring:
  application:
    name: mall-config
  profiles:
    active: native  # 使用本地配置，要使用git存储 存储改为git即可
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/{application}
#        git:
#          url: https://github.com/Springhuge/mall.git
#          username: macro
#          password: 123456
#          clone-on-start: true
#          search-paths: '{application}'